variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<cloud_sc>'
    appType: 'webAppLinux'
    appName: '<mywebapp-jack>'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'